services:
  db:
    image: postgres:16-alpine
    container_name: ai_agent_db
    restart: always

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    # TRADUÇÃO DE PORTA: Mapeia a porta 5130 da sua máquina (host)
    # para a porta 5432 do container (onde o Postgres escuta)
    ports:
      - "5130:5432"

    volumes:
      - postgres_data_gmail:/var/lib/postgresql/data

volumes:
  postgres_data_gmail: